### ISSUE TITLE
Upgrade from version 2 to 3

### ISSUE THREAD

**Issue by eerison** [satnaing/astro-paper#173]
Hello I am trying to bump astro paper from version 2 to 3 But I am facing this issue

```
root@3c1e13ce35e7:/app# npm run dev

> astro-paper@3.0.0 dev
> astro dev

/app/node_modules/@babel/core/lib/index.js:7
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/app/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/app/node_modules/@babel/core/lib/config/helpers/config-api.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.6.0
root@3c1e13ce35e7:/app# 
```

any idea why?

Note: I followed those articals
- https://astro-paper.pages.dev/posts/astro-paper-v3/
- https://astro-paper.pages.dev/posts/how-to-update-dependencies/

```
root@3c1e13ce35e7:/app# npx npm-check-updates   
Checking /app/package.json
[====================] 31/31 100%

All dependencies match the latest package versions :)
```

```
root@3c1e13ce35e7:/app# npm update

up to date, audited 990 packages in 3s

300 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by eerison** [comment]
I installed the project again, But I faced a similar issue, and it solved after I use `node 18`, I guess it is the issue, But I can't confirm because I reinstall `AstroPaper` again
